enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/E85Addicts/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

patches-version = "dev"
cli-version = "dev"

[Spotify]
enabled = true
build-mode = "both"
archive-dlurl = "https://archive.org/download/e85-apks/apks/com.spotify.music"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
version = "auto"

[TikTok]
enabled = true
build-mode = "both"
version = "latest"
patches-source = "E85Addicts/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
excluded-patches = "'Remember clear display'"
